spring.application.name=PetmaxAdmin
spring.security.user.name=admin
spring.security.user.password={noop}admin
spring.datasource.url=jdbc:postgresql://localhost:5432/bdPetmaxAdmin
spring.datasource.username=postgres
spring.datasource.password=280705
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
